name: Lint
on: [push]
jobs:
  lint-dockerfile:
    runs-on: ubuntu-20.04
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Lint dockerfile (hadolint)
        uses: hadolint/hadolint-action@v2.1.0
